
services:

  zookeeper:
     image: confluentinc/cp-zookeeper:latest
     environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
     networks:
      - appnetwork

  kafka:
    image: confluentinc/cp-kafka:7.9.1
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
    networks:
      - appnetwork
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: myserver
    environment:
      SA_PASSWORD: "Admin123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - appnetwork

  webapi:
    build:
      context: .
      dockerfile: ReactWebAPI/Dockerfile
    container_name: ReacrWebAPI
    depends_on:
      - sqlserver
      - kafka
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5000:8080"
    networks:
      - appnetwork

  webapi2:
    build:
      context: .
      dockerfile: NotificationAPI/Dockerfile
    container_name: notificationAPI
    depends_on:
      - kafka
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5001:8081"
    networks:
      - appnetwork
networks:
  appnetwork:
